# Generated by Django 5.2 on 2026-03-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionIOL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('fecha_orden', models.DateTimeField()),
                ('tipo', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('mercado', models.CharField(max_length=50)),
                ('simbolo', models.CharField(max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('modalidad', models.CharField(max_length=50)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fecha_operada', models.DateTimeField(blank=True, null=True)),
                ('cantidad_operada', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('precio_operado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('monto_operado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('plazo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['-fecha_orden'],
                'indexes': [models.Index(fields=['fecha_orden'], name='operaciones_fecha_o_13443f_idx'), models.Index(fields=['simbolo'], name='operaciones_simbolo_173a04_idx'), models.Index(fields=['estado'], name='operaciones_estado_f5d82f_idx')],
            },
        ),
    ]
