# Generated by Django 5.2 on 2026-03-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones_iol', '0002_alter_operacioniol_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacioniol',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
