# Generated by Django 5.2 on 2026-03-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones_iol', '0003_alter_operacioniol_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacioniol',
            name='aranceles_ars',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='operacioniol',
            name='aranceles_detalle',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='operacioniol',
            name='aranceles_usd',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='operacioniol',
            name='estado_actual',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='operacioniol',
            name='estados_detalle',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='operacioniol',
            name='fecha_alta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operacioniol',
            name='fondos_para_operacion',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operacioniol',
            name='moneda',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='operacioniol',
            name='monto_operacion',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='operacioniol',
            name='operaciones_detalle',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='operacioniol',
            name='validez',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operacioniol',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='operacioniol',
            name='cantidad_operada',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='operacioniol',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='operacioniol',
            name='monto_operado',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='operacioniol',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='operacioniol',
            name='precio_operado',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
    ]
