# Generated by Django 5.2 on 2026-03-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones_iol', '0004_operacioniol_aranceles_ars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacioniol',
            name='pais_consulta',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='operacioniol',
            index=models.Index(fields=['pais_consulta'], name='operacione_pais_co_7f9ad6_idx'),
        ),
    ]
