# Generated by Django 5.2 on 2026-03-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones_iol', '0005_operacioniol_pais_consulta'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='operacioniol',
            new_name='operaciones_pais_co_640e0d_idx',
            old_name='operacione_pais_co_7f9ad6_idx',
        ),
        migrations.AddConstraint(
            model_name='operacioniol',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cantidad__gte', 0), ('cantidad__isnull', True), _connector='OR'), models.Q(('monto__gte', 0), ('monto__isnull', True), _connector='OR'), models.Q(('precio__gte', 0), ('precio__isnull', True), _connector='OR'), models.Q(('cantidad_operada__gte', 0), ('cantidad_operada__isnull', True), _connector='OR'), models.Q(('precio_operado__gte', 0), ('precio_operado__isnull', True), _connector='OR'), models.Q(('monto_operado__gte', 0), ('monto_operado__isnull', True), _connector='OR'), models.Q(('monto_operacion__gte', 0), ('monto_operacion__isnull', True), _connector='OR'), models.Q(('aranceles_ars__gte', 0), ('aranceles_ars__isnull', True), _connector='OR'), models.Q(('aranceles_usd__gte', 0), ('aranceles_usd__isnull', True), _connector='OR')), name='operacion_iol_non_negative_amounts'),
        ),
    ]
