# Generated by Django 5.2 on 2026-03-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simbolo', models.CharField(max_length=20, unique=True)),
                ('sector', models.CharField(max_length=100)),
                ('bloque_estrategico', models.CharField(max_length=100)),
                ('pais_exposicion', models.CharField(max_length=50)),
                ('tipo_patrimonial', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['simbolo'],
            },
        ),
    ]
