# Generated by Django 5.2 on 2026-03-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenCuentaSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_extraccion', models.DateTimeField()),
                ('numero_cuenta', models.CharField(max_length=50)),
                ('tipo_cuenta', models.CharField(max_length=50)),
                ('moneda', models.CharField(max_length=10)),
                ('disponible', models.DecimalField(decimal_places=2, max_digits=15)),
                ('comprometido', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('titulos_valorizados', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('margen_descubierto', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-fecha_extraccion'],
                'indexes': [models.Index(fields=['fecha_extraccion'], name='resumen_iol_fecha_e_ee5a19_idx'), models.Index(fields=['numero_cuenta'], name='resumen_iol_numero__2f1271_idx')],
            },
        ),
    ]
