# Generated by Django 5.2 on 2026-03-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen_iol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumencuentasnapshot',
            name='saldos_detalle',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resumencuentasnapshot',
            name='total_en_pesos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='resumencuentasnapshot',
            name='moneda',
            field=models.CharField(max_length=50),
        ),
    ]
