# Generated by Django 5.2 on 2026-03-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoPortafolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_extraccion', models.DateTimeField()),
                ('pais_consulta', models.CharField(max_length=50)),
                ('simbolo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15)),
                ('comprometido', models.DecimalField(decimal_places=2, max_digits=15)),
                ('disponible_inmediato', models.DecimalField(decimal_places=2, max_digits=15)),
                ('puntos_variacion', models.DecimalField(decimal_places=4, max_digits=15)),
                ('variacion_diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ultimo_precio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ppc', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ganancia_porcentaje', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ganancia_dinero', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valorizado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pais_titulo', models.CharField(max_length=50)),
                ('mercado', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('plazo', models.CharField(blank=True, max_length=50, null=True)),
                ('moneda', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['-fecha_extraccion', 'simbolo'],
                'indexes': [models.Index(fields=['fecha_extraccion'], name='portafolio__fecha_e_ee5214_idx'), models.Index(fields=['simbolo'], name='portafolio__simbolo_439ace_idx'), models.Index(fields=['pais_consulta'], name='portafolio__pais_co_5b4537_idx')],
            },
        ),
    ]
