# Generated by Django 5.2 on 2026-03-09 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio_iol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('total_iol', models.DecimalField(decimal_places=2, help_text='Total IOL (activos + cash)', max_digits=15)),
                ('liquidez_operativa', models.DecimalField(decimal_places=2, help_text='Cash + caución + FCI disponibles', max_digits=15)),
                ('cash_management', models.DecimalField(decimal_places=2, help_text='FCI de cash management', max_digits=15)),
                ('portafolio_invertido', models.DecimalField(decimal_places=2, help_text='Activos de inversión', max_digits=15)),
                ('rendimiento_total', models.FloatField(help_text='Rendimiento total del portafolio (%)')),
                ('exposicion_usa', models.FloatField(help_text='Exposición a USA (%)')),
                ('exposicion_argentina', models.FloatField(help_text='Exposición a Argentina (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['fecha'], name='portafolio__fecha_3d1fe5_idx')],
            },
        ),
        migrations.CreateModel(
            name='PositionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simbolo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('valorizado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('peso', models.FloatField(help_text='Peso en el portafolio total (%)')),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('pais', models.CharField(blank=True, max_length=50)),
                ('tipo', models.CharField(blank=True, max_length=50)),
                ('bloque_estrategico', models.CharField(blank=True, max_length=100)),
                ('ganancia_dinero', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ganancia_porcentaje', models.FloatField(default=0)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='portafolio_iol.portfoliosnapshot')),
            ],
            options={
                'ordering': ['-peso'],
                'indexes': [models.Index(fields=['snapshot', 'simbolo'], name='portafolio__snapsho_6cae77_idx'), models.Index(fields=['snapshot', 'sector'], name='portafolio__snapsho_b83805_idx'), models.Index(fields=['snapshot', 'pais'], name='portafolio__snapsho_250909_idx')],
                'unique_together': {('snapshot', 'simbolo')},
            },
        ),
    ]
