# Generated by Django 5.2 on 2026-03-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio_iol', '0003_portfoliosnapshot_liquidity_layers'),
    ]

    operations = [
        migrations.AddField(
            model_name='activoportafoliosnapshot',
            name='parking',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activoportafoliosnapshot',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='activoportafoliosnapshot',
            name='comprometido',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='activoportafoliosnapshot',
            name='disponible_inmediato',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='activoportafoliosnapshot',
            name='ganancia_dinero',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='activoportafoliosnapshot',
            name='ganancia_porcentaje',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='activoportafoliosnapshot',
            name='moneda',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='activoportafoliosnapshot',
            name='ppc',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='activoportafoliosnapshot',
            name='puntos_variacion',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='activoportafoliosnapshot',
            name='ultimo_precio',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='activoportafoliosnapshot',
            name='valorizado',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='activoportafoliosnapshot',
            name='variacion_diaria',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
