# Generated by Django 5.2 on 2026-03-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio_iol', '0004_activoportafoliosnapshot_parking_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='portfoliosnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('total_iol__gte', 0), ('liquidez_operativa__gte', 0), ('cash_management__gte', 0), ('portafolio_invertido__gte', 0), models.Q(('total_patrimonio_modelado__gte', 0), ('total_patrimonio_modelado__isnull', True), _connector='OR'), models.Q(('cash_disponible_broker__gte', 0), ('cash_disponible_broker__isnull', True), _connector='OR'), models.Q(('caucion_colocada__gte', 0), ('caucion_colocada__isnull', True), _connector='OR')), name='portfolio_snapshot_non_negative_amounts'),
        ),
        migrations.AddConstraint(
            model_name='portfoliosnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('exposicion_usa__gte', 0), ('exposicion_usa__lte', 100), ('exposicion_argentina__gte', 0), ('exposicion_argentina__lte', 100)), name='portfolio_snapshot_exposure_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='positionsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('valorizado__gte', 0)), name='position_snapshot_non_negative_valorizado'),
        ),
        migrations.AddConstraint(
            model_name='positionsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('peso__gte', 0), ('peso__lte', 100)), name='position_snapshot_weight_range_valid'),
        ),
    ]
