# Generated by Django 5.2 on 2026-03-27 04:38

from django.db import migrations, models


def _bounded_percentage(value):
    try:
        numeric = float(value)
    except (TypeError, ValueError):
        return 0.0
    return max(0.0, min(100.0, numeric))


def sanitize_legacy_snapshot_exposures(apps, schema_editor):
    PortfolioSnapshot = apps.get_model('portafolio_iol', 'PortfolioSnapshot')
    PositionSnapshot = apps.get_model('portafolio_iol', 'PositionSnapshot')

    invalid_snapshots = PortfolioSnapshot.objects.filter(
        models.Q(exposicion_usa__lt=0)
        | models.Q(exposicion_usa__gt=100)
        | models.Q(exposicion_argentina__lt=0)
        | models.Q(exposicion_argentina__gt=100)
    )

    for snapshot in invalid_snapshots.iterator():
        positions = PositionSnapshot.objects.filter(snapshot_id=snapshot.id).values('pais', 'peso')

        if positions.exists():
            usa_exposure = 0.0
            argentina_exposure = 0.0

            for row in positions:
                country = str(row.get('pais') or '').strip().lower()
                weight = float(row.get('peso') or 0.0)
                if country == 'usa':
                    usa_exposure += weight
                elif country == 'argentina':
                    argentina_exposure += weight

            snapshot.exposicion_usa = _bounded_percentage(usa_exposure)
            snapshot.exposicion_argentina = _bounded_percentage(argentina_exposure)
        else:
            snapshot.exposicion_usa = _bounded_percentage(snapshot.exposicion_usa)
            snapshot.exposicion_argentina = _bounded_percentage(snapshot.exposicion_argentina)

        snapshot.save(update_fields=['exposicion_usa', 'exposicion_argentina'])


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio_iol', '0004_activoportafoliosnapshot_parking_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='portfoliosnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('total_iol__gte', 0), ('liquidez_operativa__gte', 0), ('cash_management__gte', 0), ('portafolio_invertido__gte', 0), models.Q(('total_patrimonio_modelado__gte', 0), ('total_patrimonio_modelado__isnull', True), _connector='OR'), models.Q(('cash_disponible_broker__gte', 0), ('cash_disponible_broker__isnull', True), _connector='OR'), models.Q(('caucion_colocada__gte', 0), ('caucion_colocada__isnull', True), _connector='OR')), name='portfolio_snapshot_non_negative_amounts'),
        ),
        migrations.RunPython(sanitize_legacy_snapshot_exposures, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='portfoliosnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('exposicion_usa__gte', 0), ('exposicion_usa__lte', 100), ('exposicion_argentina__gte', 0), ('exposicion_argentina__lte', 100)), name='portfolio_snapshot_exposure_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='positionsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('valorizado__gte', 0)), name='position_snapshot_non_negative_valorizado'),
        ),
        migrations.AddConstraint(
            model_name='positionsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('peso__gte', 0), ('peso__lte', 100)), name='position_snapshot_weight_range_valid'),
        ),
    ]
