# Generated by Django 5.2 on 2026-03-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liquidez_target', models.DecimalField(decimal_places=2, default=20.0, help_text='Porcentaje objetivo para liquidez (%)', max_digits=5)),
                ('usa_target', models.DecimalField(decimal_places=2, default=40.0, help_text='Porcentaje objetivo para activos USA (%)', max_digits=5)),
                ('argentina_target', models.DecimalField(decimal_places=2, default=30.0, help_text='Porcentaje objetivo para activos Argentina (%)', max_digits=5)),
                ('emerging_target', models.DecimalField(decimal_places=2, default=10.0, help_text='Porcentaje objetivo para mercados emergentes (%)', max_digits=5)),
                ('max_single_position', models.DecimalField(decimal_places=2, default=15.0, help_text='Máximo porcentaje por posición individual (%)', max_digits=5)),
                ('risk_free_rate', models.DecimalField(decimal_places=2, default=3.5, help_text='Tasa libre de riesgo (%)', max_digits=4)),
                ('rebalance_threshold', models.DecimalField(decimal_places=2, default=5.0, help_text='Umbral para trigger de rebalanceo (%)', max_digits=4)),
                ('is_active', models.BooleanField(default=True, help_text='Si estos parámetros están activos')),
                ('name', models.CharField(default='Parámetros Principales', help_text='Nombre descriptivo de la configuración', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parámetro de Portafolio',
                'verbose_name_plural': 'Parámetros de Portafolio',
                'ordering': ['-created_at'],
            },
        ),
    ]
