# Generated by Django 5.2 on 2026-03-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_portfolioparameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('concentracion_excesiva', 'Concentración Excesiva'), ('liquidez_excesiva', 'Liquidez Excesiva'), ('exposicion_pais', 'Exposición País'), ('exposicion_sector', 'Exposición Sector'), ('perdida_significativa', 'Pérdida Significativa')], help_text='Tipo de alerta', max_length=50)),
                ('mensaje', models.TextField(help_text='Mensaje descriptivo de la alerta')),
                ('severidad', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], help_text='Severidad de la alerta', max_length=10)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, help_text='Valor numérico relacionado con la alerta', max_digits=10, null=True)),
                ('simbolo', models.CharField(blank=True, help_text='Símbolo del activo relacionado', max_length=20, null=True)),
                ('sector', models.CharField(blank=True, help_text='Sector relacionado', max_length=100, null=True)),
                ('pais', models.CharField(blank=True, help_text='País relacionado', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Si la alerta está activa')),
                ('is_acknowledged', models.BooleanField(default=False, help_text='Si la alerta ha sido reconocida')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='Fecha de reconocimiento', null=True)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-created_at'],
            },
        ),
    ]
