# Generated by Django 5.2 on 2026-03-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sensitiveactionaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benchmark_key', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=20)),
                ('source', models.CharField(default='alpha_vantage', max_length=32)),
                ('fecha', models.DateField()),
                ('close', models.DecimalField(decimal_places=6, max_digits=18)),
                ('adjusted_close', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha', 'benchmark_key'],
                'indexes': [models.Index(fields=['benchmark_key', 'fecha'], name='core_benchm_benchma_7269f3_idx'), models.Index(fields=['symbol', 'fecha'], name='core_benchm_symbol_737450_idx')],
                'constraints': [models.UniqueConstraint(fields=('benchmark_key', 'source', 'fecha'), name='unique_benchmark_snapshot_per_day')],
            },
        ),
    ]
