# Generated by Django 5.2 on 2026-03-14 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_benchmarksnapshot_unique_benchmark_snapshot_per_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroSeriesSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_key', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=32)),
                ('external_id', models.CharField(max_length=64)),
                ('frequency', models.CharField(max_length=16)),
                ('fecha', models.DateField()),
                ('value', models.DecimalField(decimal_places=6, max_digits=18)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha', 'series_key'],
                'indexes': [models.Index(fields=['series_key', 'fecha'], name='core_macros_series__b6611c_idx'), models.Index(fields=['source', 'external_id', 'fecha'], name='core_macros_source_10bb2d_idx')],
                'constraints': [models.UniqueConstraint(fields=('series_key', 'source', 'fecha'), name='unique_macro_series_snapshot_per_day')],
            },
        ),
    ]
