# Generated by Django 5.2 on 2026-03-27 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_iolmarketsnapshotobservation_by_plazo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensitiveactionaudit',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Sensitive action audit', 'verbose_name_plural': 'Sensitive action audits'},
        ),
        migrations.RenameIndex(
            model_name='incrementalproposalsnapshot',
            new_name='core_increm_user_id_d2014b_idx',
            old_name='core_increm_user_id_72d20f_idx',
        ),
        migrations.RenameIndex(
            model_name='incrementalproposalsnapshot',
            new_name='core_increm_source__e5fda7_idx',
            old_name='core_increm_source__bf4270_idx',
        ),
        migrations.RenameIndex(
            model_name='iolfcicatalogsnapshot',
            new_name='core_iolfci_capture_491efa_idx',
            old_name='core_iolfci_captured_477b2d_idx',
        ),
        migrations.RenameIndex(
            model_name='iolfcicatalogsnapshot',
            new_name='core_iolfci_capture_32a92b_idx',
            old_name='core_iolfci_captured_e6f14e_idx',
        ),
        migrations.RenameIndex(
            model_name='iolfcicatalogsnapshot',
            new_name='core_iolfci_capture_c9645a_idx',
            old_name='core_iolfci_captured_80ce52_idx',
        ),
        migrations.RenameIndex(
            model_name='iolfcicatalogsnapshot',
            new_name='core_iolfci_capture_a993f3_idx',
            old_name='core_iolfci_captured_59e57e_idx',
        ),
        migrations.RenameIndex(
            model_name='iolfcicatalogsnapshot',
            new_name='core_iolfci_capture_8ecca2_idx',
            old_name='core_iolfci_captured_b24d42_idx',
        ),
        migrations.RenameIndex(
            model_name='iolmarketcoveragesnapshot',
            new_name='core_iolmar_capture_6a9e5a_idx',
            old_name='core_iolmar_captured_601c01_idx',
        ),
        migrations.RenameIndex(
            model_name='iolmarketcoveragesnapshot',
            new_name='core_iolmar_capture_04f791_idx',
            old_name='core_iolmar_captured_03e594_idx',
        ),
        migrations.RenameIndex(
            model_name='iolmarketcoveragesnapshot',
            new_name='core_iolmar_capture_d9fb33_idx',
            old_name='core_iolmar_captured_39c5b8_idx',
        ),
        migrations.RenameIndex(
            model_name='iolmarketsnapshotobservation',
            new_name='core_iolmar_simbolo_b87990_idx',
            old_name='core_iolmar_simbolo_2380ad_idx',
        ),
        migrations.RenameIndex(
            model_name='iolmarketsnapshotobservation',
            new_name='core_iolmar_capture_c5ea1c_idx',
            old_name='core_iolmar_capture_9d3d4d_idx',
        ),
        migrations.RenameIndex(
            model_name='iolmarketsnapshotobservation',
            new_name='core_iolmar_capture_dd6d95_idx',
            old_name='core_iolmar_captured_1c97c8_idx',
        ),
        migrations.RenameIndex(
            model_name='iolmarketuniversesnapshot',
            new_name='core_iolmar_capture_b9ff00_idx',
            old_name='core_iolmar_capture_4dcff1_idx',
        ),
        migrations.RenameIndex(
            model_name='iolmarketuniversesnapshot',
            new_name='core_iolmar_capture_1c5eb9_idx',
            old_name='core_iolmar_capture_fae12a_idx',
        ),
        migrations.RenameIndex(
            model_name='iolmarketuniversesnapshot',
            new_name='core_iolmar_capture_14a6d6_idx',
            old_name='core_iolmar_capture_8e3324_idx',
        ),
    ]
