# Generated by Django 5.2 on 2026-03-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_sensitiveactionaudit_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinvizFundamentalsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_symbol', models.CharField(max_length=24)),
                ('finviz_symbol', models.CharField(max_length=24)),
                ('source', models.CharField(default='finviz', max_length=32)),
                ('captured_at', models.DateTimeField()),
                ('captured_date', models.DateField()),
                ('source_status', models.CharField(default='ok', max_length=16)),
                ('data_quality', models.CharField(default='partial', max_length=16)),
                ('mapped_reason', models.CharField(blank=True, default='', max_length=64)),
                ('tipo_patrimonial', models.CharField(blank=True, default='', max_length=32)),
                ('sector', models.CharField(blank=True, default='', max_length=64)),
                ('country', models.CharField(blank=True, default='', max_length=64)),
                ('strategic_bucket', models.CharField(blank=True, default='', max_length=64)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('change_pct', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('beta', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('pe', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('fwd_pe', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('peg', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('ps', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('pb', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('pc', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('pfcf', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('eps_this_y', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('eps_next_y', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('eps_past_5y', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('eps_next_5y', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('sales_past_5y', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('roa', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('roe', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('roic', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('curr_r', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('quick_r', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('lt_debt_eq', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('debt_eq', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('gross_m', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('oper_m', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('profit_m', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('dividend', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-captured_date', 'internal_symbol'],
                'indexes': [models.Index(fields=['captured_date', 'source_status'], name='core_finviz_capture_64958e_idx'), models.Index(fields=['captured_date', 'strategic_bucket'], name='core_finviz_capture_2fed60_idx'), models.Index(fields=['captured_date', 'sector'], name='core_finviz_capture_9d2225_idx')],
                'constraints': [models.UniqueConstraint(fields=('internal_symbol', 'source', 'captured_date'), name='unique_finviz_fundamentals_snapshot_per_day')],
            },
        ),
    ]
