# Generated by Django 5.2 on 2026-03-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_finvizfundamentalssnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinvizSignalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_symbol', models.CharField(max_length=24)),
                ('finviz_symbol', models.CharField(max_length=24)),
                ('source', models.CharField(default='finviz_signal', max_length=32)),
                ('captured_at', models.DateTimeField()),
                ('captured_date', models.DateField()),
                ('source_status', models.CharField(default='ok', max_length=16)),
                ('mapped_reason', models.CharField(blank=True, default='', max_length=64)),
                ('ratings_count', models.PositiveIntegerField(default=0)),
                ('ratings_positive_count', models.PositiveIntegerField(default=0)),
                ('ratings_negative_count', models.PositiveIntegerField(default=0)),
                ('ratings_neutral_count', models.PositiveIntegerField(default=0)),
                ('analyst_score', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('analyst_signal_label', models.CharField(blank=True, default='', max_length=32)),
                ('news_count', models.PositiveIntegerField(default=0)),
                ('insider_buy_count', models.PositiveIntegerField(default=0)),
                ('insider_sale_count', models.PositiveIntegerField(default=0)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-captured_date', 'internal_symbol'],
                'indexes': [models.Index(fields=['captured_date', 'source_status'], name='core_finviz_capture_c24cb4_idx'), models.Index(fields=['captured_date', 'analyst_signal_label'], name='core_finviz_capture_2ae9f5_idx')],
                'constraints': [models.UniqueConstraint(fields=('internal_symbol', 'source', 'captured_date'), name='unique_finviz_signal_snapshot_per_day')],
            },
        ),
    ]
