name: Validate secrets

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  security-secrets-validation:
    runs-on: ubuntu-latest
    env:
      FASTAPI_TOKENS_KEY: ${{ secrets.FASTAPI_TOKENS_KEY }}
      IOL_TOKENS_KEY: ${{ secrets.IOL_TOKENS_KEY }}
      APP_ENV: prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate security environment
        run: python -m shared.security_env_validator
